version: "3.7"

services:
  # TDEX daemon connected to Blockstream.info explorer
  tdexd:
    container_name: "tdexd"
    image: ghcr.io/tdex-network/tdexd:latest
    restart: unless-stopped
    environment:
      - TDEX_LOG_LEVEL=4 # 5 for Debug. 4 for production
      - TDEX_CRAWL_INTERVAL=5000 # 5 seconds to poll blockchain
      - TDEX_CRAWL_LIMIT=5000
      - TDEX_CRAWL_TOKEN=500
      - TDEX_EXPLORER_ENDPOINT=${EXPLORER} # 5 seconds to poll blockchain
      
      #### Macaroons auth/TLS termination - Operator interface ####
      # Uncomment to disable macaroons auth
      #- TDEX_NO_MACAROONS=true

      # Uncomment one or both if running on a remote host with auth enabled
      #- TDEX_OPERATOR_EXTRA_IP=0.0.0.0
      #- TDEX_OPERATOR_EXTRA_DOMAIN=your.dns.domain
      
      #### TLS only - Trade interface ####
      # Uncomment also the volumes down that mount to this paths
      #- TDEX_SSL_CERT=./trade.crt
      #- TDEX_SSL_KEY=./trade.key
      #### Uncomment to unlock on startup ####
      #- TDEX_WALLET_UNLOCK_PASSWORD_FILE:./pwd.txt
    ports:
      - "9945:9945"
      - "9000:9000"
      
    volumes:
      - ./tdexd:/home/user/.tdex-daemon
      #### TLS only ####
      #- ${SSL_CERT_PATH}:/trade.crt
      #- ${SSL_KEY_PATH}:/trade.key
      #### Unlock on startup ####
      #- ${PWD_PATH}:/pwd.txt

  # Pull prices from kraken and push to the daemon
  feederd:
    container_name: "feederd"
    image: ghcr.io/tdex-network/feederd:latest
    restart: unless-stopped
    depends_on:
      - tdexd
    volumes:
      - ./feederd/config.json:/config.json
      # Uncomment to mount TLS cert and mac files sourced from daemon datadir on this service.
      # - ./tdexd/macaroons/price.macaroon:/price.macaroon
      # - ./tdexd/tls/cert.pem:/cert.pem
